---
language: python

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/aptly
  matrix:
    - VERSION=latest
    - VERSION=1.3.0
    - VERSION=1.4.0

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
